language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: khAXXM+M0I9ZvkQNlTDo97hhBBJTkspMT9en8CoBjkHIk1i3xus57SEzHoJWO3D3SIx+gmpEcYZLJJaF2eoXK+0nLz1ZfUIgVzmUQ0uzzGNh/dwH0ayDs8YhpwhPoIdEWDyNe8BqBYFTv6s3Rn2gLEL/9CcPvSB9mkkqjzm7wyZb8LazPCCIFlsogXZHznZn5OiLFN1XFBHG+VTI6dK0/KA8fq1WuJCp5Y9wUZMLs1l1ev8Opd9fUq04TCjtn20J8HRfnavues04WH2D8dG8h0Mxb5klaWJdjHgI4YSg3IFXbSBrOE2qXXlDIzlet5Sg0+jIQUKAzSRltMq6MMebTDpvLKPUFWcsMwdFPTGTxIGgaOGqyEaUZjwJ6OxWvizIIRlreDdc7jvTQNrB3dDv5dLmnsOGTipY2N1M9k9Bpg6s7EkY9HllLwLXTHyK9C7ZZps21a8m1e7c7rIyq/16PxuOp9MM8acaAv5eGu1elFx/d9UFEtWxVp3Y8VvnaashdqmyHUYCUXATlUJ8/ZeNHbzFxbPkMAgA+WDAuDJMuDslS0Kzvgs38jl96zmsSCDy3X8bfEQMJFsZmh2CaWycNI1haL8LU9fPEwHecF4ZBFScczdWZVo44Qt8y2yz6/R8Wtgz91qh8L0NJvtuXWHPIVNM/yGaf5ECsD0yyRCObvs=
  app: poke-planner
  skip_cleanup: true 